// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/countries": {
    params: {};
  };
  "/countries/:countryName": {
    params: {
      "countryName": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/countries" | "/countries/:countryName";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/countries.tsx": {
    id: "routes/countries";
    page: "/countries";
  };
  "routes/country.tsx": {
    id: "routes/country";
    page: "/countries/:countryName";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/countries": typeof import("./app/routes/countries.tsx");
  "routes/country": typeof import("./app/routes/country.tsx");
};